### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by ghost** [Galts-Gulch/avarice#14]
Periodically I will get this error that shows up. Once it does show, it will continue to get post with each new candle.

Candle: 808 | Price: 1488.9 cny | Time: 08:05:10 | Date: 2015/02/24
EMA : We are in a Downtrend | Diff: -0.0049897973570223846
Exception in thread Thread-621:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 1187, in run
    self.function(_self.args, *_self.kwargs)
  File "C:\AvariceSimulation\genutils.py", line 15, in do_every
    worker_func()
  File "C:\AvariceSimulation\avarice.py", line 37, in RunCommon
    getattr(indicators, indicator).indicator()
  File "C:\AvariceSimulation\indicators.py", line 255, in indicator
    gc.FRAMA.ShortPeriod))
  File "C:\AvariceSimulation\indicators.py", line 52, in FRAMA
    \* (Helpers.FractalDimension(list1, period1) - 1))
  File "C:\AvariceSimulation\indicators.py", line 47, in FractalDimension
    D = (math.log(N1 + N2) - math.log(N3)) / math.log(2)
ValueError: math domain error

**Comment by RealJohnGalt** [comment]
Thank you for catching this. I'll be sure to fix this bug shortly. After 05b83b0f4 , this only affects FRAMA and other indicators continue generating data.

**Comment by RealJohnGalt** [comment]
This and similar bugs have been fixed in ea18e9f88, f8a0835f, and f72e2f7c.
