### ISSUE TITLE
XMPP module import error

### ISSUE THREAD

**Issue by ghost** [Galts-Gulch/avarice#22]
I did perform the pip3 install xmpp_logging_handle and attempted to get Avarice to use my own xmpp server. Avarice version is 4.0.1, setting xmpp false for Simulator and Trader results in Avarice loading correctly. I fully admit I may not of configured it correctly.

Traceback (most recent call last):
  File "C:\Avarice\avarice.py", line 4, in <module>
    import avarice
  File "C:\Avarice\avarice.py", line 10, in <module>
    import notifier as no
  File "C:\Avarice\notifier.py", line 10, in <module>
    from xmpp_logging_handler import XMPPHandler
  File "C:\Python34\lib\site-packages\xmpp_logging_handler__init__.py", line 2,
 in <module>
    from emitter import Send
ImportError: No module named 'emitter'

I looked for "emitter" but haven't found much about it. Seems to get referenced for YAML. But seems to be a completely different module.

**Comment by RealJohnGalt** [comment]
I don't believe xmpp_logging_handler was fully or correctly installed. xmpp_logging_handler comes with an emitter module (https://github.com/Level-Up/xmpp_logging_handler/blob/master/xmpp_logging_handler/emitter.py). I just tested an uninstall and re-install to verify I got the file in my site-packages/xmpp_logging_handler/ directory.

Unfortunately, I can't recreate this. Perhaps you could try a pip3 uninstall and install of it again, watching out for any errors? In the uninstall list, you should also see the emitter module listed.

**Comment by ghost** [comment]
Doing that now, I'll keep you posted on how it goes. Thank you

**Comment by ghost** [comment]
Still fails, I uninstalled and reinstalled. Here is the successful installation of  the XMPP logging handler

C:\Python34>pip3 install xmpp_logging_handler
Collecting xmpp-logging-handler
  Downloading xmpp_logging_handler-1.0.2.tar.gz
Collecting xmpppy (from xmpp-logging-handler)
  Downloading xmpppy-0.5.0rc1.tar.gz (59kB)
    100% |################################| 61kB 758kB/s
Installing collected packages: xmpppy, xmpp-logging-handler
  Running setup.py install for xmpppy
  Running setup.py install for xmpp-logging-handler
Successfully installed xmpp-logging-handler-1.0.2 xmpppy-0.5.0rc1

Enabled XMPP and this is the result again.
Traceback (most recent call last):
  File "C:\Avarice\avarice.py", line 4, in <module>
    import avarice
  File "C:\Avarice\avarice.py", line 10, in <module>
    import notifier as no
  File "C:\Avarice\notifier.py", line 10, in <module>
    from xmpp_logging_handler import XMPPHandler
  File "C:\Python34\lib\site-packages\xmpp_logging_handler__init__.py", line 2,
 in <module>
    from emitter import Send
ImportError: No module named 'emitter'

Could it be a formatting problem? My XMPP server the username is setup at as username@domain.com

I've tried just the username and using the username@domain.com with the same response.

**Comment by RealJohnGalt** [comment]
It's not a formatting problem, it's actually a bad standalone package. It's not just you, sorry I missed this. I'm going to implement a different way of handling this and properly test it on a fresh system.

**Comment by ghost** [comment]
Ahhh, okay, let me know if you need a hand testing. :)

**Comment by RealJohnGalt** [comment]
Will do, I appreciate it. I'm about to go AFK so can't do this now. But I'll be removing this (broken) functionality from the main branch, and re-implementing it in the staging branch since that will need quite a bit of testing as a "pre-release" shortly (within a day) anyway :). It would also need rewriting to the new config format if I did it in the master branch. Here's a bit of a teaser for what's been done in that pre-release in the last few hours https://cloud.githubusercontent.com/assets/7730016/6883659/46c09d5c-d575-11e4-9b9f-00c87cd43449.png

Thank you again.

**Comment by ghost** [comment]
Very nice, definitely looking forward to the new configuration utility.

**Comment by RealJohnGalt** [comment]
XMPP slated for v5.0a2 (second v5.0 testing release, first to come soon).

**Comment by RealJohnGalt** [comment]
The project is no longer being maintained, in favor of a new code base in a new language. See #43 for info.
