### ISSUE TITLE
Possible Input bug

### ISSUE THREAD

**Issue by ghost** [Galts-Gulch/avarice#34]
I keep getting the following error:

C:\Avarice>avarice.py
Database is recent enough; resuming
[API] Connecting to Public OKCoin WebSocket...
[API] Connecting to Public OKCoin WebSocket...
Waiting 5.89 minutes to resume on schedule
[API] Connecting to Public OKCoin WebSocket...
Candle: 1483 | Price: 2276.54 cny | Time: 13:58:53 | Date: 2015/11/02
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python34\lib\shelve.py", line 111, in **getitem**
    value = self.cache[key]
KeyError: 'MACD_Short_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 1186, in run
    self.function(_self.args, *_self.kwargs)
  File "C:\Avarice\genutils.py", line 16, in do_every
    worker_func()
  File "C:\Avarice\avarice.py", line 133, in RCWrapper
    gu.do_every(ldb.CandleSizeSeconds, RunCommon)
  File "C:\Avarice\genutils.py", line 16, in do_every
    worker_func()
  File "C:\Avarice\avarice.py", line 104, in RunCommon
    RunIndicator(i)
  File "C:\Avarice\avarice.py", line 87, in RunIndicator
    ind.indicator()
  File "C:\Avarice\indicators.py", line 317, in indicator
    ldb.price_list, storage.getlist('MACD_Short_list'), ShortPeriod))
  File "C:\Avarice\storage.py", line 42, in writelist
    temp = db[ln]
  File "C:\Python34\lib\shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
EOFError: Ran out of input

**Comment by RealJohnGalt** [comment]
This is fixed locally, I'll push shortly. I've just been trudging through API support recently for server/client avarice.
