### ISSUE TITLE
error when clean the database?

### ISSUE THREAD

**Issue by mailsol** [Galts-Gulch/avarice#35]
Hello, Thanks for the great software! 

I getting the following error with staging branch, 
when database **Store All** set to **False**:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 1186, in run
    self.function(_self.args, *_self.kwargs)
  File "/root/avarice/staging/genutils.py", line 16, in do_every
    worker_func()
  File "avarice.py", line 133, in RCWrapper
    gu.do_every(ldb.CandleSizeSeconds, RunCommon)
  File "/root/avarice/staging/genutils.py", line 16, in do_every
    worker_func()
  File "avarice.py", line 98, in RunCommon
    ldb.PopulateRow()
  File "/root/avarice/staging/loggerdb.py", line 244, in PopulateRow
    .format(tn=table_name, cn=i, **lim=avarice.MaxCandleDepends**))
sqlite3.IntegrityError: datatype mismatch

**Comment by mailsol** [comment]
I have resolved this issue by ceil the value.
