### ISSUE TITLE
[Issue?] XMPP Dependacies

### ISSUE THREAD

**Issue by ghostnegotiator** [Galts-Gulch/avarice#39]
When installing the dependencies for XMPP I get the following:

```
Could not find a version that satisfies the requirement xmpppy (from xmpp-logging-handler->-r requirements.txt (line 5)) (from versions: 0.5.0rc1)
Cleaning up...
No distributions matching the version for xmpppy (from xmpp-logging-handler->-r requirements.txt (line 5))
Storing debug log for failure in /home/rdash/.pip/pip.log
```

Debug log:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
pip.exceptions.DistributionNotFound: No distributions matching the version for xmpppy (from xmpp-logging-handler->-r requirements.txt (line 5))
```

**Comment by ghostnegotiator** [comment]
Seems that XMPPPY is Decapitated...

https://pypi.python.org/pypi/xmpppy/0.5.0rc1

**Comment by ghostnegotiator** [comment]
Successfully installed it by adding xmpppy to the requirements.txt

**Comment by ghostnegotiator** [comment]
Sorry this is a duplicate of #22
