### ISSUE TITLE
[BUG] Exception with advanced strategy

### ISSUE THREAD

**Issue by ghostnegotiator** [Galts-Gulch/avarice#40]
This occours when using different strategies

```
  Trade Indicators = ['MACD', 'RSI']
```

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 1186, in run
    self.function(*self.args, **self.kwargs)
  File "/home/rdash/avarice/genutils.py", line 16, in do_every
    worker_func()
  File "avarice.py", line 133, in RCWrapper
    gu.do_every(ldb.CandleSizeSeconds, RunCommon)
  File "/home/rdash/avarice/genutils.py", line 16, in do_every
    worker_func()
  File "avarice.py", line 107, in RunCommon
    getattr(strategies, config.gc['Trader']['Advanced Strategy'])()
  File "/home/rdash/avarice/strategies.py", line 209, in Default
    if IndList[-1] < LocalBid:
TypeError: unorderable types: float() < str()
```

**Comment by RealJohnGalt** [comment]
What version are you running?

**Comment by ghostnegotiator** [comment]
Version 5 a2

**Comment by RealJohnGalt** [comment]
The project is no longer being maintained, in favor of a new code base in a new language. See #43 for info.
