### ISSUE TITLE
WebSocket exception

### ISSUE THREAD

**Issue by etienn01** [Galts-Gulch/avarice#41]
I'm running v5.0a2 tag, indicator is MACD and 15min candles.

```
Candle: 37 | Price: 2844.36 cny | Time: 22:33:48 | Date: 2016/01/02
MACD : We are in a Downtrend | Diff: 2.106378135454179
MACD Hist: -1.0823483829427265
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/alarm/avarice/okcoin/WebSocketAPI.py", line 94, in userinfo
    info = self.ws.recv()
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 348, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 365, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 378, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 410, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python3.5/site-packages/websocket/_abnf.py", line 312, in recv_frame
    self.recv_header()
  File "/usr/lib/python3.5/site-packages/websocket/_abnf.py", line 261, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python3.5/site-packages/websocket/_abnf.py", line 346, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 479, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python3.5/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/home/alarm/avarice/genutils.py", line 16, in do_every
    worker_func()
  File "avarice.py", line 133, in RCWrapper
    gu.do_every(ldb.CandleSizeSeconds, RunCommon)
  File "/home/alarm/avarice/genutils.py", line 16, in do_every
    worker_func()
  File "avarice.py", line 110, in RunCommon
    trd.TradeFromStrategy()
  File "/home/alarm/avarice/trader.py", line 80, in TradeFromStrategy
    TradeAmount = GetTradeAmount('sell', st.Trade_dict['TradeVolume'])
  File "/home/alarm/avarice/trader.py", line 25, in GetTradeAmount
    ta = gu.RoundIfGreaterThan((volume / 100) * el.GetFree('asset'), 3)
  File "/home/alarm/avarice/exchangelayer.py", line 44, in GetFree
    okwspriv.userinfo())[-1]['data']['info']['funds']['free'][config.gc[
  File "/home/alarm/avarice/okcoin/WebSocketAPI.py", line 101, in userinfo
    info = self.ws.recv()
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 348, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 365, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 378, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 410, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python3.5/site-packages/websocket/_abnf.py", line 312, in recv_frame
    self.recv_header()
  File "/usr/lib/python3.5/site-packages/websocket/_abnf.py", line 261, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python3.5/site-packages/websocket/_abnf.py", line 346, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 479, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python3.5/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```

**Comment by RealJohnGalt** [comment]
The project is no longer being maintained, in favor of a new code base in a new language. See #43 for info.
